/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Modelo.Reportes;
import ModeloDao.ReportesDao;
import java.util.List;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Javier Pisco
 */
public class ReportMes extends javax.swing.JInternalFrame {

    DefaultTableModel modelMes = new DefaultTableModel();

    ReportesDao rdao = new ReportesDao();
    Reportes rp = new Reportes();

    /**
     * Creates new form Report
     */
    public ReportMes() {
        initComponents();
        modelMes = new DefaultTableModel();
//        modelMes.addColumn("Cliente");
//        modelMes.addColumn("Vendedor");
        modelMes.addColumn("Fecha");
        modelMes.addColumn("Monto");

        tbMes.setModel(modelMes);
        listaTotal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMes = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        cbMes = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbMes = new javax.swing.JTable();
        jToggleButton1 = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();

        btnMes.setText("Consultar");
        btnMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMesActionPerformed(evt);
            }
        });

        jLabel1.setText("Reporte por mes");

        cbMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));

        tbMes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbMes);

        jToggleButton1.setText("Exportar a Excel");

        jButton1.setText("Volver a consultar totales");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbMes, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btnMes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jToggleButton1)
                .addGap(26, 26, 26))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMes))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton1)
                    .addComponent(jButton1))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
void anterior() {
        modelMes = new DefaultTableModel();
        modelMes.addColumn("Fecha");
        modelMes.addColumn("Monto");
        tbMes.setModel(modelMes);
    }

    void nueva() {
        modelMes = new DefaultTableModel();
        modelMes.addColumn("Cliente");
        modelMes.addColumn("Vendedor");
        modelMes.addColumn("Fecha");
        modelMes.addColumn("Monto");
        tbMes.setModel(modelMes);

    }

    void listaTotal() {
        List<Reportes> lista = rdao.listartotalMes();
        modelMes = (DefaultTableModel) tbMes.getModel();
        Object[] ob = new Object[2];
        for (int i = 0; i < lista.size(); i++) {
//            ob[0] = lista.get(i).getCliente();
//            ob[1] = lista.get(i).getVendedor();
            ob[0] = lista.get(i).getFecha();
            ob[1] = lista.get(i).getMonto();
            modelMes.addRow(ob);
        }
    }
    private void btnMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMesActionPerformed
//        ReporteMes vis=new ReporteMes();
        nueva();
        String mes = (String) cbMes.getSelectedItem();
        List<Reportes> lista = rdao.listarMes(mes);
        modelMes = (DefaultTableModel) tbMes.getModel();
        Object[] ob = new Object[4];
        for (int i = 0; i < lista.size(); i++) {
            ob[0] = lista.get(i).getCliente();
            ob[1] = lista.get(i).getVendedor();
            ob[2] = lista.get(i).getFecha();
            ob[3] = lista.get(i).getMonto();
            modelMes.addRow(ob);
        }
//        tbMes.setModel(modelMes); 
//        ReMes me =new ReMes(mes);
//       ReMes.txtMes.setText(mes);
//        vis.setVisible(true);
    }//GEN-LAST:event_btnMesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        anterior();
        listaTotal();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnMes;
    public static javax.swing.JComboBox<String> cbMes;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTable tbMes;
    // End of variables declaration//GEN-END:variables
}
